name: 打包admin web 应用并上传服务器

on:
  schedule:
    # 这个是国际标准时间 非北京时间 北京时间比国际时间早8小时 所以要减去8小时 为 国际时间的1点
    - cron: '30 1 * * *'
  # schedule 的 cron 任务可能会延迟，短则几小时长则甚至可能一天 配置了 workflow_dispatch 我们就可以手动执行了
  workflow_dispatch:

# 推送之后执行一系列的任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 迁出代码
        # 使用action库 action/checkout获取大妈
        uses: actions/checkout@master
      # 安装Node10

      - name: 安装node.js
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0

      - name: 安装pnpm
        run: npm install -g pnpm@7.12.2

      # 安装依赖
      - name: 安装依赖
        run: pnpm install

      # 打包
      - name: 打包
        run: pnpm background:build

      # 上传到腾讯云
      - name: 发布到腾讯云
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # SCP参数
          ARGS: '-avzr --delete'
          # 源目录
          SOURCE: '/dist'
          # 服务器ip
          REMOTE_HOST: ${{ secrets.PRIVATE_HOST }}
          # 用户
          REMOTE_USER: 'root'
          # 目标地址 - 服务器上nginx对应访问的地址
          TARGET: '/www/server/nginx/html/admin'
